TRUNCATE TABLE CAPSTONE_DEMO.BT_SCAN_CACHE_HISTORY;
DROP TABLE CAPSTONE_DEMO.BT_SCAN_CACHE_HISTORY;
CREATE TABLE CAPSTONE_DEMO.BT_SCAN_CACHE_HISTORY

(
SNAPSHOT_TS TIMESTAMP,
SNAPSHOT_ID NUMBER,
BT_CACHE_ALLOC NUMBER,
BT_CACHE_TARGET NUMBER,
OBJECT_COUNT NUMBER,
MEMORY_BUF_ALLOC NUMBER,
MIN_CACHED_TEMP NUMBER,
CON_ID NUMBER
);

INSERT INTO CAPSTONE_DEMO.BT_SCAN_CACHE_HISTORY

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  NULL AS SNAPSHOT_TS,
  A.BT_CACHE_ALLOC,
  A.BT_CACHE_TARGET,
  A.OBJECT_COUNT,
  A.MEMORY_BUF_ALLOC,
  A.MIN_CACHED_TEMP,
  A.CON_ID
FROM V$BT_SCAN_CACHE A;

COMMIT;