TRUNCATE TABLE CAPSTONE_DEMO.SESSION_PROCESS_HISTORY;
DROP TABLE CAPSTONE_DEMO.SESSION_PROCESS_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SESSION_PROCESS_HISTORY

(
  MODULE VARCHAR2(64),
  ACTION VARCHAR2(64),
  CLIENT_INFO VARCHAR2(64),
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  SQL_EXEC_START DATE,
  SQL_ID VARCHAR2(13),
  SID NUMBER,
  SADDR VARCHAR2(32),
  PGA_USED_MEM NUMBER,
  PGA_ALLOC_MEM NUMBER,
  PGA_FREEABLE_MEM NUMBER,
  PGA_MAX_MEM NUMBER
)
PARALLEL (DEGREE DEFAULT);

INSERT INTO CAPSTONE_DEMO.SESSION_PROCESS_HISTORY

SELECT
  A.MODULE,
  A.ACTION,
  A.CLIENT_INFO,
  NULL AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.SQL_ID,
  A.SID,
  A.SADDR,
  B.PGA_USED_MEM,
  B.PGA_ALLOC_MEM,
  B.PGA_FREEABLE_MEM,
  B.PGA_MAX_MEM
FROM V$SESSION A
  INNER JOIN V$PROCESS B
    ON A.PADDR = B.ADDR
WHERE A.ACTION = 'RESOURCE_MONITORING';

SELECT
  *
FROM CAPSTONE_DEMO.SESSION_PROCESS_HISTORY
ORDER BY
  SNAPSHOT_TS DESC,
  SID;