TRUNCATE TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST;
DROP TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST;
CREATE TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

(
  MODULE VARCHAR2(64),
  ACTION VARCHAR2(64),
  CLIENT_INFO VARCHAR2(64),
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  SQL_EXEC_START DATE,
  SQL_ID VARCHAR2(13),
  SID NUMBER,
  STAT_NAME VARCHAR2(64),
  VALUE NUMBER,
  QCSID NUMBER
)
PARALLEL (DEGREE DEFAULT)
PCTFREE 0
COMPRESS FOR OLTP;

INSERT INTO CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

SELECT
  C.MODULE,
  C.ACTION,
  C.CLIENT_INFO,
  NULL AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  C.SQL_EXEC_START,
  C.SQL_ID,
  C.SID,
  A.STAT_NAME,
  A.VALUE,
  B.QCSID
FROM V$SESS_TIME_MODEL A
  INNER JOIN V$PX_SESSION B
    ON A.SID = B.SID
  INNER JOIN V$SESSION C
    ON A.SID = C.SID
WHERE C.ACTION = 'RESOURCE_MONITORING'
AND VALUE > 0;