TRUNCATE TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY;
DROP TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY

(
SNAPSHOT_TS TIMESTAMP,
SNAPSHOT_ID NUMBER,
COMPONENT VARCHAR2(64),
CURRENT_SIZE NUMBER,
MIN_SIZE NUMBER,
MAX_SIZE NUMBER,
USER_SPECIFIED_SIZE NUMBER,
OPER_COUNT NUMBER,
LAST_OPER_TYPE VARCHAR2(13),
LAST_OPER_MODE VARCHAR2(9),
LAST_OPER_TIME DATE,
GRANULE_SIZE NUMBER,
CON_ID NUMBER
);

INSERT INTO CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  NULL AS SNAPSHOT_TS,
  A.COMPONENT,
  A.CURRENT_SIZE,
  A.MIN_SIZE,
  A.MAX_SIZE,
  A.USER_SPECIFIED_SIZE,
  A.OPER_COUNT,
  A.LAST_OPER_TYPE,
  A.LAST_OPER_MODE,
  A.LAST_OPER_TIME,
  A.GRANULE_SIZE,
  A.CON_ID
FROM V$SGA_DYNAMIC_COMPONENTS A;

COMMIT;