TRUNCATE TABLE CAPSTONE_DEMO.SGA_RESIZE_OPS_HISTORY;
DROP TABLE CAPSTONE_DEMO.SGA_RESIZE_OPS_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SGA_RESIZE_OPS_HISTORY

(
SNAPSHOT_TS TIMESTAMP,
SNAPSHOT_ID NUMBER,
COMPONENT VARCHAR2(64),
OPER_TYPE VARCHAR2(13),
OPER_MODE VARCHAR2(9),
PARAMETER VARCHAR2(80),
INITIAL_SIZE NUMBER,
TARGET_SIZE NUMBER,
FINAL_SIZE NUMBER,
STATUS VARCHAR2(9),
START_TIME DATE,
END_TIME DATE,
CON_ID NUMBER
);

INSERT INTO CAPSTONE_DEMO.SGA_RESIZE_OPS_HISTORY

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  NULL AS SNAPSHOT_TS,
  A.COMPONENT,
  A.OPER_TYPE,
  A.OPER_MODE,
  A.PARAMETER,
  A.INITIAL_SIZE,
  A.TARGET_SIZE,
  A.FINAL_SIZE,
  A.STATUS,
  A.START_TIME,
  A.END_TIME,
  A.CON_ID
FROM V$SGA_RESIZE_OPS A;

COMMIT;