TRUNCATE TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY;
DROP TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY

(
  MODULE VARCHAR2(64),
  ACTION VARCHAR2(64),
  CLIENT_INFO VARCHAR2(64),
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  SQL_EXEC_START DATE,
  SQL_ID VARCHAR2(13),
  SID NUMBER,
  PX_MAXDOP NUMBER,
  PX_SERVERS_REQUESTED NUMBER,
  PX_SERVERS_ALLOCATED NUMBER,
  BUFFER_GETS NUMBER,
  DISK_READS NUMBER,
  DIRECT_WRITES NUMBER,
  IO_INTERCONNECT_BYTES NUMBER,
  PHYSICAL_READ_REQUESTS NUMBER,
  PHYSICAL_READ_BYTES NUMBER,
  PHYSICAL_WRITE_REQUESTS NUMBER,
  PHYSICAL_WRITE_BYTES NUMBER,
  USER_IO_WAIT_TIME NUMBER,
  SQL_TEXT VARCHAR2(2000)
)
PARALLEL (DEGREE DEFAULT);

INSERT INTO CAPSTONE_DEMO.SQL_MONITOR_HISTORY

SELECT
  MODULE,
  ACTION,
  CLIENT_INFO,
  NULL AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SQL_EXEC_START,
  SQL_ID,
  SID,
  PX_MAXDOP,
  PX_SERVERS_REQUESTED,
  PX_SERVERS_ALLOCATED,
  BUFFER_GETS,
  DISK_READS,
  DIRECT_WRITES,
  IO_INTERCONNECT_BYTES,
  PHYSICAL_READ_REQUESTS,
  PHYSICAL_READ_BYTES,
  PHYSICAL_WRITE_REQUESTS,
  PHYSICAL_WRITE_BYTES,
  USER_IO_WAIT_TIME,
  SQL_TEXT
FROM V$SQL_MONITOR A
WHERE A.ACTION = 'RESOURCE_MONITORING';

SELECT
  *
FROM CAPSTONE_DEMO.SQL_MONITOR_HISTORY;

SELECT
  *
FROM ALL_TAB_COLS
WHERE COLUMN_NAME = 'BUFFER_GETS'
ORDER BY
  TABLE_NAME;

SELECT 
  *
FROM V$SQLSTATS;

SELECT
  *
FROM V$SYSSTAT;