TRUNCATE TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY;
DROP TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SQL_MONITOR_HISTORY

(
  SNAPSHOT_TS TIMESTAMP,
  SNAPSHOT_ID NUMBER,
  KEY NUMBER,
  REPORT_ID NUMBER,
  STATUS VARCHAR2(19),
  USER# NUMBER,
  USERNAME VARCHAR2(30),
  MODULE VARCHAR2(64),
  ACTION VARCHAR2(64),
  SERVICE_NAME VARCHAR2(64),
  CLIENT_IDENTIFIER VARCHAR2(64),
  CLIENT_INFO VARCHAR2(64),
  PROGRAM VARCHAR2(48),
  PLSQL_ENTRY_OBJECT_ID NUMBER,
  PLSQL_ENTRY_SUBPROGRAM_ID NUMBER,
  PLSQL_OBJECT_ID NUMBER,
  PLSQL_SUBPROGRAM_ID NUMBER,
  FIRST_REFRESH_TIME DATE,
  LAST_REFRESH_TIME DATE,
  REFRESH_COUNT NUMBER,
  DBOP_EXEC_ID NUMBER,
  DBOP_NAME VARCHAR2(30),
  SID NUMBER,
  PROCESS_NAME VARCHAR2(5),
  SQL_ID VARCHAR2(13),
  SQL_TEXT VARCHAR2(2000),
  IS_FULL_SQLTEXT VARCHAR2(1),
  SQL_EXEC_START DATE,
  SQL_EXEC_ID NUMBER,
  SQL_PLAN_HASH_VALUE NUMBER,
  SQL_FULL_PLAN_HASH_VALUE NUMBER,
  EXACT_MATCHING_SIGNATURE NUMBER,
  FORCE_MATCHING_SIGNATURE NUMBER,
  SQL_CHILD_ADDRESS RAW(8),
  SESSION_SERIAL# NUMBER,
  PX_IS_CROSS_INSTANCE VARCHAR2(1),
  PX_MAXDOP NUMBER,
  PX_MAXDOP_INSTANCES NUMBER,
  PX_SERVERS_REQUESTED NUMBER,
  PX_SERVERS_ALLOCATED NUMBER,
  PX_SERVER# NUMBER,
  PX_SERVER_GROUP NUMBER,
  PX_SERVER_SET NUMBER,
  PX_QCINST_ID NUMBER,
  PX_QCSID NUMBER,
  ERROR_NUMBER VARCHAR2(40),
  ERROR_FACILITY VARCHAR2(4),
  ERROR_MESSAGE VARCHAR2(256),
  BINDS_XML CLOB,
  OTHER_XML CLOB,
  ELAPSED_TIME NUMBER,
  QUEUING_TIME NUMBER,
  CPU_TIME NUMBER,
  FETCHES NUMBER,
  BUFFER_GETS NUMBER,
  DISK_READS NUMBER,
  DIRECT_WRITES NUMBER,
  IO_INTERCONNECT_BYTES NUMBER,
  PHYSICAL_READ_REQUESTS NUMBER,
  PHYSICAL_READ_BYTES NUMBER,
  PHYSICAL_WRITE_REQUESTS NUMBER,
  PHYSICAL_WRITE_BYTES NUMBER,
  APPLICATION_WAIT_TIME NUMBER,
  CONCURRENCY_WAIT_TIME NUMBER,
  CLUSTER_WAIT_TIME NUMBER,
  USER_IO_WAIT_TIME NUMBER,
  PLSQL_EXEC_TIME NUMBER,
  JAVA_EXEC_TIME NUMBER,
  RM_LAST_ACTION VARCHAR2(48),
  RM_LAST_ACTION_REASON VARCHAR2(30),
  RM_LAST_ACTION_TIME DATE,
  RM_CONSUMER_GROUP VARCHAR2(30),
  CON_ID NUMBER,
  CON_NAME VARCHAR2(30),
  ECID VARCHAR2(64),
  IS_ADAPTIVE_PLAN VARCHAR2(1),
  IS_FINAL_PLAN VARCHAR2(1)
)
PARALLEL (DEGREE DEFAULT);

INSERT INTO CAPSTONE_DEMO.SQL_MONITOR_HISTORY 

WITH MONITOR_ME AS

(
SELECT 
  MAX(SQL_EXEC_START) AS SQL_EXEC_START
FROM V$SQL_MONITOR
WHERE ACTION = 'RESOURCE_MONITORING'
)

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  NULL AS SNAPSHOT_ID,
  A.KEY,
  A.REPORT_ID,
  A.STATUS,
  A.USER#,
  A.USERNAME,
  A.MODULE,
  A.ACTION,
  A.SERVICE_NAME,
  A.CLIENT_IDENTIFIER,
  A.CLIENT_INFO,
  A.PROGRAM,
  A.PLSQL_ENTRY_OBJECT_ID,
  A.PLSQL_ENTRY_SUBPROGRAM_ID,
  A.PLSQL_OBJECT_ID,
  A.PLSQL_SUBPROGRAM_ID,
  A.FIRST_REFRESH_TIME,
  A.LAST_REFRESH_TIME,
  A.REFRESH_COUNT,
  A.DBOP_EXEC_ID,
  A.DBOP_NAME,
  A.SID,
  A.PROCESS_NAME,
  A.SQL_ID,
  A.SQL_TEXT,
  A.IS_FULL_SQLTEXT,
  A.SQL_EXEC_START,
  A.SQL_EXEC_ID,
  A.SQL_PLAN_HASH_VALUE,
  A.SQL_FULL_PLAN_HASH_VALUE,
  A.EXACT_MATCHING_SIGNATURE,
  A.FORCE_MATCHING_SIGNATURE,
  A.SQL_CHILD_ADDRESS,
  A.SESSION_SERIAL#,
  A.PX_IS_CROSS_INSTANCE,
  A.PX_MAXDOP,
  A.PX_MAXDOP_INSTANCES,
  A.PX_SERVERS_REQUESTED,
  A.PX_SERVERS_ALLOCATED,
  A.PX_SERVER#,
  A.PX_SERVER_GROUP,
  A.PX_SERVER_SET,
  A.PX_QCINST_ID,
  A.PX_QCSID,
  A.ERROR_NUMBER,
  A.ERROR_FACILITY,
  A.ERROR_MESSAGE,
  A.BINDS_XML,
  A.OTHER_XML,
  A.ELAPSED_TIME,
  A.QUEUING_TIME,
  A.CPU_TIME,
  A.FETCHES,
  A.BUFFER_GETS,
  A.DISK_READS,
  A.DIRECT_WRITES,
  A.IO_INTERCONNECT_BYTES,
  A.PHYSICAL_READ_REQUESTS,
  A.PHYSICAL_READ_BYTES,
  A.PHYSICAL_WRITE_REQUESTS,
  A.PHYSICAL_WRITE_BYTES,
  A.APPLICATION_WAIT_TIME,
  A.CONCURRENCY_WAIT_TIME,
  A.CLUSTER_WAIT_TIME,
  A.USER_IO_WAIT_TIME,
  A.PLSQL_EXEC_TIME,
  A.JAVA_EXEC_TIME,
  A.RM_LAST_ACTION,
  A.RM_LAST_ACTION_REASON,
  A.RM_LAST_ACTION_TIME,
  A.RM_CONSUMER_GROUP,
  A.CON_ID,
  A.CON_NAME,
  A.ECID,
  A.IS_ADAPTIVE_PLAN,
  A.IS_FINAL_PLAN
FROM V$SQL_MONITOR A
  INNER JOIN MONITOR_ME B
    ON A. SQL_EXEC_START = B.SQL_EXEC_START;

WITH EXPERIMENT_FILTER AS

(
SELECT
  *
FROM CAPSTONE_DEMO.TIME_USAGE_SUMMARY_V
WHERE MODULE = 'STATEMENT_QUEUING_QUICK'
--AND CLIENT_INFO = 'SINGLE_TABLE_ANALYTICS_V1'
--AND PARALLEL_DEGREE_POLICY = 'POLICY = ADAPTIVE'
)

SELECT
  *
FROM CAPSTONE_DEMO.SQL_MONITOR_HISTORY A
  INNER JOIN EXPERIMENT_FILTER C
    ON A.SQL_EXEC_START = C.SQL_EXEC_START;
ORDER BY
  A.SNAPSHOT_TS;
  
WITH EXPERIMENT_FILTER AS

(
SELECT DISTINCT
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START
FROM CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST
WHERE MODULE IN ('STATEMENT_QUEUING_QUICK PDP = AUTO', 'STATEMENT_QUEUING_QUICK PDP = MANUAL')
AND SQL_EXEC_START IS NOT NULL
ORDER BY
  SQL_EXEC_START,
  CLIENT_INFO
)

SELECT /*+ PARALLEL(16) */
  A.MODULE,
  A.CLIENT_INFO,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.SQL_EXEC_ID,
  SUM(A.BUFFER_GETS) AS BUFFER_GETS,
  SUM(A.DISK_READS) AS DISK_READS,
  SUM(A.DIRECT_WRITES) AS DIRECT_WRITES,
  SUM(A.IO_INTERCONNECT_BYTES)/POWER(1024,3) AS IO_INTERCONNECT_GB,
  SUM(A.PHYSICAL_READ_REQUESTS) AS PHYSICAL_READ_REQUESTS,
  SUM(A.PHYSICAL_READ_BYTES)/POWER(1024,3) AS PHYSICAL_READ_GB,
  SUM(A.PHYSICAL_WRITE_REQUESTS) AS PHYSICAL_WRITE_REQUESTS,
  SUM(A.PHYSICAL_WRITE_BYTES)/POWER(1024,3) AS PHYSICAL_WRITE_GB,
  SUM(A.USER_IO_WAIT_TIME) AS USER_IO_WAIT_TIME
FROM CAPSTONE_DEMO.SQL_MONITOR_HISTORY A
  INNER JOIN EXPERIMENT_FILTER B
    ON A.SQL_EXEC_START = B.SQL_EXEC_START
GROUP BY
  A.MODULE,
  A.CLIENT_INFO,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.SQL_EXEC_ID;
  
SELECT
  *
FROM V$ACTIVE_SESSION_HISTORY
WHERE MODULE = 'STATEMENT_QUEUING_QUICK';