TRUNCATE TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY;
DROP TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY

(
  MODULE VARCHAR2(64),
  ACTION VARCHAR2(64),
  CLIENT_INFO VARCHAR2(64),
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  SQL_EXEC_START DATE,
  SQL_ID VARCHAR2(13),
  SID NUMBER,
  OPERATION_TYPE VARCHAR2(40),
  OPERATION_ID NUMBER,
  WORK_AREA_SIZE NUMBER,
  EXPECTED_SIZE NUMBER,
  ACTUAL_MEM_USED NUMBER,
  MAX_MEM_USED NUMBER,
  NUMBER_PASSES NUMBER,
  TEMPSEG_SIZE NUMBER
)
PARALLEL (DEGREE DEFAULT);

INSERT INTO CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY

SELECT
  B.MODULE,
  B.ACTION,
  B.CLIENT_INFO,
  NULL AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  B.SQL_EXEC_START,
  B.SQL_ID,
  B.SID,
  A.OPERATION_TYPE,
  A.OPERATION_ID,
  A.WORK_AREA_SIZE,
  A.EXPECTED_SIZE,
  A.ACTUAL_MEM_USED,
  A.MAX_MEM_USED,
  A.NUMBER_PASSES,
  A.TEMPSEG_SIZE
FROM V$SQL_WORKAREA_ACTIVE A
  INNER JOIN V$SESSION B
    ON A.SID = B.SID
WHERE B.ACTION = 'RESOURCE_MONITORING';