PROCEDURE RESOURCE_USAGE_MONITORING_V2(LOOP_COUNT NUMBER, TIME_BETWEEN_LOOPS NUMBER) AS

BEGIN

FOR A IN 1..LOOP_COUNT LOOP

INSERT INTO CAPSTONE_DEMO.SQL_MONITOR_HISTORY

SELECT
  MODULE,
  ACTION,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SID,
  SQL_ID,
  SQL_EXEC_START,
  PX_MAXDOP,
  PX_SERVERS_REQUESTED,
  PX_SERVERS_ALLOCATED,
  BUFFER_GETS,
  DISK_READS,
  DIRECT_WRITES,
  IO_INTERCONNECT_BYTES,
  PHYSICAL_READ_REQUESTS,
  PHYSICAL_READ_BYTES,
  PHYSICAL_WRITE_REQUESTS,
  PHYSICAL_WRITE_BYTES,
  USER_IO_WAIT_TIME,
  SQL_TEXT
FROM V$SQL_MONITOR A
WHERE ACTION = 'RESOURCE_MONITORING';

INSERT INTO CAPSTONE_DEMO.SESSION_PROCESS_HISTORY

SELECT
  A.MODULE,
  A.ACTION,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  A.SADDR,
  A.SID,
  A.SQL_ID,
  A.SQL_EXEC_START,
  B.PGA_USED_MEM,
  B.PGA_ALLOC_MEM,
  B.PGA_FREEABLE_MEM,
  B.PGA_MAX_MEM
FROM V$SESSION A
  INNER JOIN V$PROCESS B
    ON A.PADDR = B.ADDR
WHERE A.ACTION = 'RESOURCE_MONITORING';

INSERT INTO CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY


SELECT 
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SQL_ID,
  SQL_EXEC_START ,
  OPERATION_TYPE,
  OPERATION_ID,
  SID,
  WORK_AREA_SIZE,
  EXPECTED_SIZE,
  ACTUAL_MEM_USED,
  MAX_MEM_USED,
  NUMBER_PASSES,
  TEMPSEG_SIZE
FROM V$SQL_WORKAREA_ACTIVE A;

INSERT INTO CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

SELECT
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  A.STAT_NAME,
  A.VALUE,
  B.QCSID,
  B.SID
FROM V$SESS_TIME_MODEL A
  INNER JOIN V$PX_SESSION B
    ON A.SID = B.SID
WHERE A.SID IN (SELECT SID FROM V$SESSION WHERE ACTION = 'RESOURCE_MONITORING')
AND VALUE > 0;

COMMIT;

DBMS_LOCK.SLEEP(SECONDS => TIME_BETWEEN_LOOPS);

END LOOP;

END RESOURCE_USAGE_MONITORING_V2;