PROCEDURE RESOURCE_USAGE_MONITORING_V2(LOOP_COUNT NUMBER, TIME_BETWEEN_LOOPS NUMBER) AS

BEGIN

FOR A IN 1..LOOP_COUNT LOOP

INSERT INTO CAPSTONE_DEMO.SQL_MONITOR_HISTORY

SELECT
  MODULE,
  ACTION,
  CLIENT_INFO,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SQL_EXEC_START,
  SQL_ID,
  SID,
  PX_MAXDOP,
  PX_SERVERS_REQUESTED,
  PX_SERVERS_ALLOCATED,
  BUFFER_GETS,
  DISK_READS,
  DIRECT_WRITES,
  IO_INTERCONNECT_BYTES,
  PHYSICAL_READ_REQUESTS,
  PHYSICAL_READ_BYTES,
  PHYSICAL_WRITE_REQUESTS,
  PHYSICAL_WRITE_BYTES,
  USER_IO_WAIT_TIME,
  SQL_TEXT
FROM V$SQL_MONITOR A
WHERE A.ACTION = 'RESOURCE_MONITORING';

INSERT INTO CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY

SELECT
  B.MODULE,
  B.ACTION,
  B.CLIENT_INFO,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  B.SQL_EXEC_START,
  B.SQL_ID,
  B.SID,
  A.OPERATION_TYPE,
  A.OPERATION_ID,
  A.WORK_AREA_SIZE,
  A.EXPECTED_SIZE,
  A.ACTUAL_MEM_USED,
  A.MAX_MEM_USED,
  A.NUMBER_PASSES,
  A.TEMPSEG_SIZE
FROM V$SQL_WORKAREA_ACTIVE A
  INNER JOIN V$SESSION B
    ON A.SID = B.SID
WHERE B.ACTION = 'RESOURCE_MONITORING';

INSERT INTO CAPSTONE_DEMO.SESSION_PROCESS_HISTORY

SELECT
  A.MODULE,
  A.ACTION,
  A.CLIENT_INFO,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.SQL_ID,
  A.SID,
  A.SADDR,
  B.PGA_USED_MEM,
  B.PGA_ALLOC_MEM,
  B.PGA_FREEABLE_MEM,
  B.PGA_MAX_MEM
FROM V$SESSION A
  INNER JOIN V$PROCESS B
    ON A.PADDR = B.ADDR
WHERE A.ACTION = 'RESOURCE_MONITORING';

INSERT INTO CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

SELECT
  C.MODULE,
  C.ACTION,
  C.CLIENT_INFO,
  A AS SNAPSHOT_ID,
  SYSTIMESTAMP AS SNAPSHOT_TS,
  C.SQL_ID,
  C.SQL_EXEC_START,
  A.STAT_NAME,
  A.VALUE,
  B.QCSID
FROM V$SESS_TIME_MODEL A
  INNER JOIN V$PX_SESSION B
    ON A.SID = B.SID
  INNER JOIN V$SESSION C
    ON A.SID = C.SID
WHERE C.ACTION = 'RESOURCE_MONITORING'
AND VALUE > 0;

COMMIT;

DBMS_LOCK.SLEEP(SECONDS => TIME_BETWEEN_LOOPS);

END LOOP;

END RESOURCE_USAGE_MONITORING_V2;