CREATE OR REPLACE VIEW CAPSTONE_DEMO.FILTER_PARENT_CHILD_JOIN_V1 AS

SELECT
  COUNT(*) AS TOTAL_ROWS
FROM CAPSTONE_DEMO.PARENT_TABLE_V1 A
  INNER JOIN CAPSTONE_DEMO.CHILD_TABLE_V1 B
    ON A.PARENT_KEY = B.PARENT_KEY
WHERE A.DEVICE_KEY = 11
AND A.DEVICE_LOCAL_TIME >= SYSDATE - 365;