CREATE OR REPLACE VIEW CAPSTONE_DEMO.LEAD_LAG_V1 AS SELECT * FROM

(
WITH LEAD_LAG AS

(
SELECT
  A.DEVICE_ID,
  A.DEVICE_LOCAL_TIME,
  A.LOCATION_KEY,
  A.SERIAL_NUMBER,
  LEAD(SERIAL_NUMBER) OVER(PARTITION BY A.DEVICE_ID, A.LOCATION_KEY ORDER BY DEVICE_LOCAL_TIME) AS NEXT_SERIAL_NUMBER,
  LAG(SERIAL_NUMBER) OVER(PARTITION BY A.DEVICE_ID, A.LOCATION_KEY ORDER BY DEVICE_LOCAL_TIME) AS PREVIOUS_SERIAL_NUMBER
FROM CAPSTONE_DEMO.LEAD_LAG_TEST_V1 A
WHERE A.DEVICE_ID = 11
)

SELECT
  COUNT(*) AS TOTAL_ROWS
FROM LEAD_LAG A
WHERE SERIAL_NUMBER <> NEXT_SERIAL_NUMBER
OR SERIAL_NUMBER <> PREVIOUS_SERIAL_NUMBER
OR PREVIOUS_SERIAL_NUMBER IS NULL
OR NEXT_SERIAL_NUMBER IS NULL
);