CREATE OR REPLACE VIEW CAPSTONE_DEMO.PARENT_CHILD_ANALYTICS_V1 AS

WITH TESTING AS

(
SELECT
  A.PARENT_KEY,
  A.DEVICE_KEY,
  B.LOCATION_KEY,
  AVG(B.MEASUREMENT_VALUE) AS AVG_MEAS_VALUE,
  COUNT(*) AS TOTAL_ROWS
FROM CAPSTONE_DEMO.PARENT_TABLE_V1 A
  INNER JOIN CAPSTONE_DEMO.CHILD_TABLE_V1 B
    ON A.PARENT_KEY = B.PARENT_KEY
WHERE A.DEVICE_KEY IN (11, 12)
GROUP BY
  A.PARENT_KEY,
  A.DEVICE_KEY,
  B.LOCATION_KEY
)

SELECT
  DEVICE_KEY,
  MAX(AVG_MEAS_VALUE) AS MAX_AVG,
  SUM(TOTAL_ROWS) AS TOTAL_ROWS
FROM TESTING
GROUP BY
  DEVICE_KEY;