CREATE OR REPLACE VIEW CAPSTONE_DEMO.TABLE_IMCS_SETTINGS_V AS

WITH ALL_TABLES_MOD AS

(
SELECT
  SNAPSHOT_TS,
  TABLE_NAME,
  INMEMORY,
  INMEMORY_COMPRESSION,
  INMEMORY || '-' || NVL(INMEMORY_COMPRESSION, 'NA') AS VALUE,
  LAG(INMEMORY || '-' || NVL(INMEMORY_COMPRESSION, 'NA')) OVER(PARTITION BY OWNER, TABLE_NAME ORDER BY SNAPSHOT_TS) AS PREVIOUS_VALUE,
  LEAD(INMEMORY || '-' || NVL(INMEMORY_COMPRESSION, 'NA')) OVER(PARTITION BY OWNER, TABLE_NAME ORDER BY SNAPSHOT_TS) AS NEXT_VALUE,
  FIRST_VALUE(SNAPSHOT_TS) OVER(PARTITION BY OWNER, TABLE_NAME ORDER BY SNAPSHOT_TS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS FIRST_SNAPSHOT_TS
FROM CAPSTONE_DEMO.ALL_TABLES_HISTORY
)

SELECT
  A.TABLE_NAME,
  A.INMEMORY_COMPRESSION,
  A.SNAPSHOT_TS AS START_TIME,
  NVL(LEAD(A.SNAPSHOT_TS) OVER(PARTITION BY A.TABLE_NAME ORDER BY A.SNAPSHOT_TS),SYSTIMESTAMP) AS END_TIME
FROM ALL_TABLES_MOD A
WHERE 
(
VALUE <> NEXT_VALUE
OR VALUE <> PREVIOUS_VALUE
OR PREVIOUS_VALUE IS NULL
);
  
SELECT
  *
FROM CAPSTONE_DEMO.TABLE_IMCS_SETTINGS_V
ORDER BY
  START_TIME DESC;


SELECT
  *
FROM CAPSTONE_DEMO.ALL_TABLES_HISTORY
ORDER BY
  SNAPSHOT_TS DESC;