DROP TABLE CAPSTONE_DEMO.DATE_DIM;
TRUNCATE TABLE CAPSTONE_DEMO.DATE_DIM;
CREATE TABLE CAPSTONE_DEMO.DATE_DIM

(
CALENDAR_DT DATE,
DATE_HOURS DATE,
DATE_MINUTES DATE,
DATE_SECONDS DATE
);

BEGIN

FOR X IN 1..2 LOOP

INSERT INTO CAPSTONE_DEMO.DATE_DIM

WITH START_DATE AS

(
SELECT
  CASE
    WHEN MAX(DATE_SECONDS) IS NULL THEN TO_DATE('20160101 00:00:0', 'yyyymmdd hh24:mi:ss')
    ELSE MAX(DATE_SECONDS)
  END AS DATE_SECONDS
FROM CAPSTONE_DEMO.DATE_DIM
)

SELECT
  TO_DATE(TO_CHAR(DATE_SECONDS + ROWNUM/24/60/60, 'yyyymmdd'), 'yyyymmdd') AS CALENDAR_DT,
  TO_DATE(TO_CHAR(DATE_SECONDS + ROWNUM/24/60/60, 'yyyymmdd hh24'), 'yyyymmdd hh24') AS DATE_HOURS,
  TO_DATE(TO_CHAR(DATE_SECONDS + ROWNUM/24/60/60, 'yyyymmdd hh24:mi'), 'yyyymmdd hh24:mi') AS DATE_MINUTES,
  DATE_SECONDS + ROWNUM/24/60/60 AS DATE_SECONDS
FROM START_DATE
CONNECT BY LEVEL <= 24*60*60 - 1;

COMMIT;

END LOOP;
END;
/
SELECT
  MIN(DATE_SECONDS) AS MIN_DATE_SECONDS,
  MAX(DATE_SECONDS) AS MAX_DATE_SECONDS,
  COUNT(*) AS TOTAL_ROWS
FROM CAPSTONE_DEMO.DATE_DIM
ORDER BY
  DATE_SECONDS DESC;