TRUNCATE TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY;
DROP TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY

(
SNAPSHOT_TS TIMESTAMP,
SNAPSHOT_ID NUMBER,
COMPONENT VARCHAR2(64),
CURRENT_SIZE NUMBER,
MIN_SIZE NUMBER,
MAX_SIZE NUMBER,
USER_SPECIFIED_SIZE NUMBER,
OPER_COUNT NUMBER,
LAST_OPER_TYPE VARCHAR2(13),
LAST_OPER_MODE VARCHAR2(9),
LAST_OPER_TIME DATE,
GRANULE_SIZE NUMBER,
CON_ID NUMBER
);

INSERT INTO CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  NULL AS SNAPSHOT_TS,
  A.COMPONENT,
  A.CURRENT_SIZE,
  A.MIN_SIZE,
  A.MAX_SIZE,
  A.USER_SPECIFIED_SIZE,
  A.OPER_COUNT,
  A.LAST_OPER_TYPE,
  A.LAST_OPER_MODE,
  A.LAST_OPER_TIME,
  A.GRANULE_SIZE,
  A.CON_ID
FROM V$SGA_DYNAMIC_COMPONENTS A;

COMMIT;

WITH EXPERIMENT_FILTER AS

(
SELECT
  *
FROM CAPSTONE_DEMO.TIME_USAGE_SUMMARY_V
WHERE MODULE = 'DB_BIG_TABLE_CACHE_EXPERIMENT'
AND CLIENT_INFO = 'SINGLE_TABLE_ANALYTICS_V1'
AND PARALLEL_DEGREE_POLICY = 'POLICY = ADAPTIVE'
)

SELECT
  C.MODULE,
  C.CLIENT_INFO,
  C.SQL_EXEC_START,
  C.RUN_NUMBER,
  C.PARALLEL_DEGREE_POLICY,
  C.BT_CACHE_TARGET,
  A.*
FROM CAPSTONE_DEMO.SGA_DYNAMIC_COMPONENTS_HISTORY A
  INNER JOIN EXPERIMENT_FILTER C
    ON A.SNAPSHOT_TS BETWEEN C.SQL_EXEC_START AND C.SQL_EXEC_END
ORDER BY
  A.SNAPSHOT_TS;