TRUNCATE TABLE CAPSTONE_DEMO.SQL_PLAN_MONITOR_HISTORY;
DROP TABLE CAPSTONE_DEMO.SQL_PLAN_MONITOR_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SQL_PLAN_MONITOR_HISTORY
(
SNAPSHOT_TS TIMESTAMP,
SNAPSHOT_ID NUMBER,
CON_ID NUMBER,
KEY NUMBER,
STATUS VARCHAR2(19),
FIRST_REFRESH_TIME DATE,
LAST_REFRESH_TIME DATE,
FIRST_CHANGE_TIME DATE,
LAST_CHANGE_TIME DATE,
REFRESH_COUNT NUMBER,
SID NUMBER,
PROCESS_NAME VARCHAR2(5),
SQL_ID VARCHAR2(13),
SQL_EXEC_START DATE,
SQL_EXEC_ID NUMBER,
SQL_PLAN_HASH_VALUE NUMBER,
SQL_CHILD_ADDRESS RAW(8),
PLAN_PARENT_ID NUMBER,
PLAN_LINE_ID NUMBER,
PLAN_OPERATION VARCHAR2(30),
PLAN_OPTIONS VARCHAR2(30),
PLAN_OBJECT_OWNER VARCHAR2(30),
PLAN_OBJECT_NAME VARCHAR2(30),
PLAN_OBJECT_TYPE VARCHAR2(20),
PLAN_DEPTH NUMBER,
PLAN_POSITION NUMBER,
PLAN_COST NUMBER,
PLAN_CARDINALITY NUMBER,
PLAN_BYTES NUMBER,
PLAN_TIME NUMBER,
PLAN_PARTITION_START VARCHAR2(64),
PLAN_PARTITION_STOP VARCHAR2(64),
PLAN_CPU_COST NUMBER,
PLAN_IO_COST NUMBER,
PLAN_TEMP_SPACE NUMBER,
STARTS NUMBER,
OUTPUT_ROWS NUMBER,
IO_INTERCONNECT_BYTES NUMBER,
PHYSICAL_READ_REQUESTS NUMBER,
PHYSICAL_READ_BYTES NUMBER,
PHYSICAL_WRITE_REQUESTS NUMBER,
PHYSICAL_WRITE_BYTES NUMBER,
WORKAREA_MEM NUMBER,
WORKAREA_MAX_MEM NUMBER,
WORKAREA_TEMPSEG NUMBER,
WORKAREA_MAX_TEMPSEG NUMBER,
OTHERSTAT_GROUP_ID NUMBER,
OTHERSTAT_1_ID NUMBER,
OTHERSTAT_1_TYPE NUMBER,
OTHERSTAT_1_VALUE NUMBER,
OTHERSTAT_2_ID NUMBER,
OTHERSTAT_2_TYPE NUMBER,
OTHERSTAT_2_VALUE NUMBER,
OTHERSTAT_3_ID NUMBER,
OTHERSTAT_3_TYPE NUMBER,
OTHERSTAT_3_VALUE NUMBER,
OTHERSTAT_4_ID NUMBER,
OTHERSTAT_4_TYPE NUMBER,
OTHERSTAT_4_VALUE NUMBER,
OTHERSTAT_5_ID NUMBER,
OTHERSTAT_5_TYPE NUMBER,
OTHERSTAT_5_VALUE NUMBER,
OTHERSTAT_6_ID NUMBER,
OTHERSTAT_6_TYPE NUMBER,
OTHERSTAT_6_VALUE NUMBER,
OTHERSTAT_7_ID NUMBER,
OTHERSTAT_7_TYPE NUMBER,
OTHERSTAT_7_VALUE NUMBER,
OTHERSTAT_8_ID NUMBER,
OTHERSTAT_8_TYPE NUMBER,
OTHERSTAT_8_VALUE NUMBER,
OTHERSTAT_9_ID NUMBER,
OTHERSTAT_9_TYPE NUMBER,
OTHERSTAT_9_VALUE NUMBER,
OTHERSTAT_10_ID NUMBER,
OTHERSTAT_10_TYPE NUMBER,
OTHERSTAT_10_VALUE NUMBER,
OTHER_XML CLOB,
PLAN_OPERATION_INACTIVE NUMBER
);


INSERT INTO CAPSTONE_DEMO.SQL_PLAN_MONITOR_HISTORY


WITH MONITOR_ME AS

(
SELECT 
  MAX(SQL_EXEC_START) AS SQL_EXEC_START
FROM V$SQL_MONITOR
WHERE ACTION = 'RESOURCE_MONITORING'
)

SELECT
SYSTIMESTAMP AS SNAPSHOT_TS,
NULL AS SNAPSHOT_ID,
A.CON_ID,
A.KEY,
A.STATUS,
A.FIRST_REFRESH_TIME,
A.LAST_REFRESH_TIME,
A.FIRST_CHANGE_TIME,
A.LAST_CHANGE_TIME,
A.REFRESH_COUNT,
A.SID,
A.PROCESS_NAME,
A.SQL_ID,
A.SQL_EXEC_START,
A.SQL_EXEC_ID,
A.SQL_PLAN_HASH_VALUE,
A.SQL_CHILD_ADDRESS,
A.PLAN_PARENT_ID,
A.PLAN_LINE_ID,
A.PLAN_OPERATION,
A.PLAN_OPTIONS,
A.PLAN_OBJECT_OWNER,
A.PLAN_OBJECT_NAME,
A.PLAN_OBJECT_TYPE,
A.PLAN_DEPTH,
A.PLAN_POSITION,
A.PLAN_COST,
A.PLAN_CARDINALITY,
A.PLAN_BYTES,
A.PLAN_TIME,
A.PLAN_PARTITION_START,
A.PLAN_PARTITION_STOP,
A.PLAN_CPU_COST,
A.PLAN_IO_COST,
A.PLAN_TEMP_SPACE,
A.STARTS,
A.OUTPUT_ROWS,
A.IO_INTERCONNECT_BYTES,
A.PHYSICAL_READ_REQUESTS,
A.PHYSICAL_READ_BYTES,
A.PHYSICAL_WRITE_REQUESTS,
A.PHYSICAL_WRITE_BYTES,
A.WORKAREA_MEM,
A.WORKAREA_MAX_MEM,
A.WORKAREA_TEMPSEG,
A.WORKAREA_MAX_TEMPSEG,
A.OTHERSTAT_GROUP_ID,
A.OTHERSTAT_1_ID,
A.OTHERSTAT_1_TYPE,
A.OTHERSTAT_1_VALUE,
A.OTHERSTAT_2_ID,
A.OTHERSTAT_2_TYPE,
A.OTHERSTAT_2_VALUE,
A.OTHERSTAT_3_ID,
A.OTHERSTAT_3_TYPE,
A.OTHERSTAT_3_VALUE,
A.OTHERSTAT_4_ID,
A.OTHERSTAT_4_TYPE,
A.OTHERSTAT_4_VALUE,
A.OTHERSTAT_5_ID,
A.OTHERSTAT_5_TYPE,
A.OTHERSTAT_5_VALUE,
A.OTHERSTAT_6_ID,
A.OTHERSTAT_6_TYPE,
A.OTHERSTAT_6_VALUE,
A.OTHERSTAT_7_ID,;
A.OTHERSTAT_7_TYPE,
A.OTHERSTAT_7_VALUE,
A.OTHERSTAT_8_ID,
A.OTHERSTAT_8_TYPE,
A.OTHERSTAT_8_VALUE,
A.OTHERSTAT_9_ID,
A.OTHERSTAT_9_TYPE,
A.OTHERSTAT_9_VALUE,
A.OTHERSTAT_10_ID,
A.OTHERSTAT_10_TYPE,
A.OTHERSTAT_10_VALUE,
A.OTHER_XML,
A.PLAN_OPERATION_INACTIVE
FROM V$SQL_PLAN_MONITOR A
  INNER JOIN MONITOR_ME B
    ON A.SQL_EXEC_START = B.SQL_EXEC_START;

COMMIT;

WITH EXPERIMENT_FILTER AS

(
SELECT
  *
FROM CAPSTONE_DEMO.EXPERIMENT_SUMMARY_V
WHERE MODULE = 'DB_BIG_TABLE_CACHE_EXPERIMENT'
AND CLIENT_INFO = 'PARENT_CHILD_ANALYTICS_V1'
AND BT_CACHE_TARGET IN ('BT_CACHE = 90%', 'BT_CACHE = 10%')
AND PARALLEL_DEGREE_POLICY = 'POLICY = AUTO'
AND RUN_NUMBER = 3
)

SELECT /*+ PARALLEL(32) */
  B.MODULE,
  B.CLIENT_INFO,
  B.DOP,
  B."_PGA_MAX_SIZE",
  B.BT_CACHE_TARGET,
  B.PARALLEL_DEGREE_POLICY,
  B.DB_CACHE_SIZE,
  B.IM_SIZE,
  B.IM_COMPRESS_LEVEL,
  B.RUN_TIME_SEC,
  CAPSTONE_DEMO.INTERVAL_TO_SEC(A.SNAPSHOT_TS - A.SQL_EXEC_START) AS MOVING_RUN_TIME_SEC,
  B.SQL_EXEC_START,
  A.SNAPSHOT_TS,
  A.KEY,
  A.STATUS,
  A.FIRST_REFRESH_TIME,
  A.LAST_REFRESH_TIME,
  A.FIRST_CHANGE_TIME,
  A.LAST_CHANGE_TIME,
  A.REFRESH_COUNT,
  A.SID,
  A.PROCESS_NAME,
  A.PLAN_PARENT_ID,
  A.PLAN_LINE_ID,
  A.PLAN_OPERATION,
  A.PLAN_OPTIONS,
  A.PLAN_OBJECT_OWNER,
  A.PLAN_OBJECT_NAME,
  A.PLAN_OBJECT_TYPE,
  A.PLAN_DEPTH,
  A.PLAN_POSITION,
  A.PLAN_COST,
  A.PLAN_CARDINALITY,
  A.PLAN_BYTES,
  A.PLAN_TIME,
  A.PLAN_PARTITION_START,
  A.PLAN_PARTITION_STOP,
  A.PLAN_CPU_COST,
  A.PLAN_IO_COST,
  A.PLAN_TEMP_SPACE,
  A.STARTS,
  A.OUTPUT_ROWS,
  A.IO_INTERCONNECT_BYTES,
  A.PHYSICAL_READ_REQUESTS,
  A.PHYSICAL_READ_BYTES,
  A.PHYSICAL_WRITE_REQUESTS,
  A.PHYSICAL_WRITE_BYTES,
  A.WORKAREA_MEM,
  A.WORKAREA_MAX_MEM,
  A.WORKAREA_TEMPSEG,
  A.WORKAREA_MAX_TEMPSEG
FROM CAPSTONE_DEMO.SQL_PLAN_MONITOR_HISTORY A
  INNER JOIN EXPERIMENT_FILTER B
    ON A.SQL_EXEC_START = B.SQL_EXEC_START
WHERE CAPSTONE_DEMO.INTERVAL_TO_SEC(A.SNAPSHOT_TS - A.SQL_EXEC_START) <= B.RUN_TIME_SEC
ORDER BY
  SNAPSHOT_TS DESC,
  LAST_REFRESH_TIME DESC,
  PLAN_LINE_ID;
  
SELECT
  *
FROM CAPSTONE_DEMO.PARENT_CHILD_ANALYTICS_V1;