CREATE OR REPLACE PACKAGE CAPSTONE_DEMO.RESOURCE_MONITOR AS 

PROCEDURE RESOURCE_USAGE_MONITORING(VIEW_NAME VARCHAR2);
  
END RESOURCE_MONITOR;
/

CREATE OR REPLACE PACKAGE BODY CAPSTONE_DEMO.RESOURCE_MONITOR AS 

PROCEDURE RESOURCE_USAGE_MONITORING(VIEW_NAME VARCHAR2) AS

BEGIN

INSERT INTO CAPSTONE_DEMO.RESOURCE_USAGE_MONITORING

WITH FINDING_SQL_START AS --DONT_FIND_ME

(
SELECT DISTINCT
  LAST_VALUE(SQL_ID) OVER(ORDER BY SQL_EXEC_START ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SQL_ID,
  LAST_VALUE(SQL_EXEC_START) OVER(ORDER BY SQL_EXEC_START ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SQL_EXEC_START,
  LAST_VALUE(SID) OVER(ORDER BY SQL_EXEC_START ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SID
FROM V$SQL_MONITOR
WHERE SQL_TEXT LIKE '%FIND_ME%'
AND SQL_TEXT NOT LIKE '%DONT_FIND_ME%'
),

FINDING_SIDS AS

(

SELECT
  SQL_ID,
  SQL_EXEC_START,
  SID
FROM V$SESSION
WHERE SQL_EXEC_START = (SELECT SQL_EXEC_START FROM FINDING_SQL_START)
),

TESTING AS

(
SELECT 
  C.SQL_ID,
  C.SQL_EXEC_START,
  B.QCSID,
  B.SID,
  A.STAT_NAME,
  A.VALUE
FROM V$SESS_TIME_MODEL A
  INNER JOIN V$PX_SESSION B
    ON A.SID = B.SID
  INNER JOIN FINDING_SIDS C
    ON B.SID = C.SID
),

TESTING_PIVOT AS

(
SELECT
  *
FROM TESTING
PIVOT (
  SUM(VALUE)
  FOR STAT_NAME IN ('DB time' AS DB_TIME, 'sql execute elapsed time' AS ELAPSED_TIME, 'DB CPU' AS CPU_TIME)
  )
)

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SQL_EXEC_START,
  SQL_ID,
  QCSID,
  SID,
  DB_TIME/1E6 AS DB_TIME_SEC,
  ELAPSED_TIME/1E6 AS ELAPSED_TIME_SEC,
  CPU_TIME/1E6 AS CPU_TIME_SEC
FROM TESTING_PIVOT A;

COMMIT;

END RESOURCE_USAGE_MONITORING;

END RESOURCE_MONITOR;
/
