TRUNCATE TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST;
DROP TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST;
CREATE TABLE CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

(
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  STAT_NAME VARCHAR2(64),
  VALUE NUMBER,
  QCSID NUMBER,
  SID NUMBER
)
PARALLEL (DEGREE DEFAULT)
PCTFREE 0
COMPRESS FOR OLTP;

INSERT INTO CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST

SELECT
  SYSTIMESTAMP AS SNAPSHOT_TS,
  A.STAT_NAME,
  A.VALUE,
  B.QCSID,
  B.SID
FROM V$SESS_TIME_MODEL A
  INNER JOIN V$PX_SESSION B
    ON A.SID = B.SID
WHERE A.SID IN (SELECT SID FROM V$SESSION WHERE ACTION = 'RESOURCE_MONITORING')
AND VALUE > 0;