TRUNCATE TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY;
DROP TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY;
CREATE TABLE CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY

(
  SNAPSHOT_ID NUMBER,
  SNAPSHOT_TS TIMESTAMP,
  SQL_ID VARCHAR2(13),
  SQL_EXEC_START DATE,
  OPERATION_TYPE VARCHAR2(40),
  OPERATION_ID NUMBER,
  SID NUMBER,
  WORK_AREA_SIZE NUMBER,
  EXPECTED_SIZE NUMBER,
  ACTUAL_MEM_USED NUMBER,
  MAX_MEM_USED NUMBER,
  NUMBER_PASSES NUMBER,
  TEMPSEG_SIZE NUMBER
)
PARALLEL (DEGREE DEFAULT);

INSERT INTO CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY

SELECT 
  SYSTIMESTAMP AS SNAPSHOT_TS,
  SQL_ID,
  SQL_EXEC_START ,
  OPERATION_TYPE,
  OPERATION_ID,
  SID,
  WORK_AREA_SIZE,
  EXPECTED_SIZE,
  ACTUAL_MEM_USED,
  MAX_MEM_USED,
  NUMBER_PASSES,
  TEMPSEG_SIZE
FROM V$SQL_WORKAREA_ACTIVE A;