CREATE OR REPLACE VIEW CAPSTONE_DEMO.CPU_USAGE_SUMMARY_V AS SELECT * FROM 

(
WITH SESS_TIME_MOD AS

(
SELECT
  A.MODULE,
  A.ACTION,
  A.CLIENT_INFO,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  ROUND(CAPSTONE_DEMO.INTERVAL_TO_SEC(A.SNAPSHOT_TS - A.SQL_EXEC_START),0) AS RUN_TIME_SEC,
  A.SQL_ID,
  A.STAT_NAME,
  A.SID,
  VALUE
FROM CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST A
WHERE A.SQL_EXEC_START IS NOT NULL
),

SESS_TIME_MOD_PIVOT AS

(
SELECT
  *
FROM SESS_TIME_MOD
PIVOT(
      SUM(VALUE/1E6)
      FOR STAT_NAME IN (
                        'DB time' AS DB_TIME, 
                        'sql execute elapsed time' AS ELAPSED_TIME, 
                        'DB CPU' AS CPU_TIME
                       )
      )
)

SELECT
  A.MODULE,
  A.ACTION,
  A.CLIENT_INFO,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.RUN_TIME_SEC,
  A.SQL_ID,
  (COUNT(*) - 1)/2 AS DOP,
  SUM(DB_TIME) AS DB_TIME,
  MAX(ELAPSED_TIME) AS WALL_TIME,
  SUM(CPU_TIME) AS CPU_TIME,
  ((COUNT(*) - 1)/2)/(SUM(DB_TIME)/MAX(ELAPSED_TIME)) AS PEI_V1,
  ((COUNT(*) - 1)/2)/(SUM(DB_TIME)/RUN_TIME_SEC) AS PEI_V2
FROM SESS_TIME_MOD_PIVOT A
GROUP BY
  A.MODULE,
  A.ACTION,
  A.CLIENT_INFO,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.RUN_TIME_SEC,
  A.SQL_ID
);

  
SELECT
  MODULE,
  ACTION,
  CLIENT_INFO,
  SQL_EXEC_START,
  MAX(RUN_TIME_SEC) AS RUN_TIME_SEC,
  MAX(DOP) AS DOP,
  MAX(DB_TIME) AS DB_TIME_SEC,
  MAX(WALL_TIME) AS WALL_TIME_SEC,
  MAX(DOP)/(MAX(DB_TIME)/MAX(RUN_TIME_SEC)) AS PEI
FROM CAPSTONE_DEMO.CPU_USAGE_SUMMARY_V
GROUP BY
  MODULE,
  ACTION,
  CLIENT_INFO,
  SQL_EXEC_START
ORDER BY
  SQL_EXEC_START,
  CLIENT_INFO,
  MODULE;
  
SELECT * FROM CAPSTONE_DEMO.SESS_TIME_MODEL_PX_SESS_HIST
WHERE ;