CREATE OR REPLACE VIEW CAPSTONE_DEMO.DOP_PARAMETERS_V AS

SELECT
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START,
  (COUNT(DISTINCT SID) - 1)/2 AS DOP,
  B.DISPLAY_VALUE AS "_PGA_MAX_SIZE"
FROM CAPSTONE_DEMO.SESSION_PROCESS_HISTORY A
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V B
    ON A.SQL_EXEC_START BETWEEN B.START_TIME AND B.END_TIME
    AND B.NAME = '_pga_max_size'
WHERE SQL_EXEC_START IS NOT NULL
HAVING (COUNT(DISTINCT SID) - 1)/2 > 1
GROUP BY
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START,
  B.DISPLAY_VALUE
ORDER BY
  SQL_EXEC_START;
  
SELECT
  *
FROM CAPSTONE_DEMO.DOP_PARAMETERS_V;