CREATE OR REPLACE VIEW CAPSTONE_DEMO.DOP_PARAMETERS_V AS

SELECT
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START,
  'DOP = ' || (COUNT(DISTINCT SID) - 1)/2 AS DOP,
  B.DISPLAY_VALUE AS "_PGA_MAX_SIZE",
  C.DISPLAY_VALUE AS DB_BIG_TABLE_CACHE_PERCENT,
  D.DISPLAY_VALUE AS PARALLEL_DEGREE_POLICY,
  E.DISPLAY_VALUE AS DB_CACHE_SIZE
FROM CAPSTONE_DEMO.SESSION_PROCESS_HISTORY A
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V B
    ON A.SQL_EXEC_START BETWEEN B.START_TIME AND B.END_TIME
    AND B.NAME = '_pga_max_size'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V C
    ON A.SQL_EXEC_START BETWEEN C.START_TIME AND C.END_TIME
    AND C.NAME = 'db_big_table_cache_percent_target'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V D
    ON A.SQL_EXEC_START BETWEEN D.START_TIME AND D.END_TIME
    AND D.NAME = 'parallel_degree_policy'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V E
    ON A.SQL_EXEC_START BETWEEN E.START_TIME AND E.END_TIME
    AND E.NAME = 'db_cache_size'
WHERE SQL_EXEC_START IS NOT NULL
HAVING (COUNT(DISTINCT SID) - 1)/2 > 1
GROUP BY
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START,
  B.DISPLAY_VALUE,
  C.DISPLAY_VALUE,
  D.DISPLAY_VALUE,
  E.DISPLAY_VALUE
ORDER BY
  SQL_EXEC_START DESC;
  
SELECT
  *
FROM CAPSTONE_DEMO.DOP_PARAMETERS_V;

SELECT
  *
FROM CAPSTONE_DEMO.PARAMETER_DURATIONS_V;