CREATE OR REPLACE VIEW CAPSTONE_DEMO.DOP_PARAMETERS_V AS

SELECT
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  'DOP = ' || (COUNT(DISTINCT SID) - 1)/2 AS DOP,
  'PGA_MAX_SIZE = ' || B.DISPLAY_VALUE AS "_PGA_MAX_SIZE",
  'BT_CACHE = ' || C.DISPLAY_VALUE AS DB_BIG_TABLE_CACHE_PERCENT,
  'POLICY = ' || D.DISPLAY_VALUE AS PARALLEL_DEGREE_POLICY,
  'DB_CACHE_SIZE = ' || E.DISPLAY_VALUE AS DB_CACHE_SIZE,
  'IM_SIZE = ' || F.DISPLAY_VALUE AS IM_SIZE,
  G.INMEMORY_COMPRESSION AS IM_COMPRESS_LEVEL
FROM CAPSTONE_DEMO.SESSION_PROCESS_HISTORY A
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V B
    ON A.SQL_EXEC_START BETWEEN B.START_TIME AND B.END_TIME
    AND B.NAME = '_pga_max_size'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V C
    ON A.SQL_EXEC_START BETWEEN C.START_TIME AND C.END_TIME
    AND C.NAME = 'db_big_table_cache_percent_target'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V D
    ON A.SQL_EXEC_START BETWEEN D.START_TIME AND D.END_TIME
    AND D.NAME = 'parallel_degree_policy'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V E
    ON A.SQL_EXEC_START BETWEEN E.START_TIME AND E.END_TIME
    AND E.NAME = 'db_cache_size'
  INNER JOIN CAPSTONE_DEMO.PARAMETER_DURATIONS_V F
    ON A.SQL_EXEC_START BETWEEN F.START_TIME AND F.END_TIME
    AND F.NAME = 'inmemory_size'
  INNER JOIN CAPSTONE_DEMO.TABLE_IMCS_SETTINGS_V G
    ON A.SQL_EXEC_START BETWEEN G.START_TIME AND G.END_TIME
    AND G.TABLE_NAME = 'LEAD_LAG_TEST_V1'
WHERE SQL_EXEC_START IS NOT NULL
HAVING (COUNT(DISTINCT SID) - 1)/2 > 1
GROUP BY
  MODULE,
  CLIENT_INFO,
  SQL_EXEC_START,
  B.DISPLAY_VALUE,
  C.DISPLAY_VALUE,
  D.DISPLAY_VALUE,
  E.DISPLAY_VALUE,
  F.DISPLAY_VALUE,
  G.INMEMORY_COMPRESSION;
  
SELECT
  *
FROM CAPSTONE_DEMO.DOP_PARAMETERS_V
ORDER BY
  SQL_EXEC_START DESC;

SELECT
  *
FROM CAPSTONE_DEMO.PARAMETER_DURATIONS_V;