CREATE OR REPLACE VIEW CAPSTONE_DEMO.INMEMORY_COMPRESSION_V AS

WITH COMPRESSION_BY_SEGMENT AS

(
SELECT 
  SEGMENT_NAME,
  INMEMORY_COMPRESSION,
  MAX(INMEMORY_SIZE)/POWER(1024,3) AS INMEMORY_SIZE_GB,
  MAX(BYTES)/POWER(1024,3) AS RAW_SIZE_GB,
  MAX(INMEMORY_SIZE)/MAX(BYTES) AS COMPRESSION_RATIO
FROM CAPSTONE_DEMO.IM_SEGMENTS_HISTORY
WHERE BYTES_NOT_POPULATED = 0
GROUP BY
  SEGMENT_NAME,
  INMEMORY_COMPRESSION
)

SELECT
  INMEMORY_COMPRESSION,
  COUNT(*) AS TOTAL_TABLES,
  SUM(RAW_SIZE_GB) AS RAW_SIZE_GB,
  SUM(INMEMORY_SIZE_GB) AS INMEMORY_SIZE_GB,
  SUM(RAW_SIZE_GB)/SUM(INMEMORY_SIZE_GB) AS COMPRESSION_RATIO
FROM COMPRESSION_BY_SEGMENT
GROUP BY
  INMEMORY_COMPRESSION;
  
SELECT
  *
FROM CAPSTONE_DEMO.INMEMORY_COMPRESSION_V
ORDER BY
  INMEMORY_COMPRESSION;

SELECT
  *
FROM CAPSTONE_DEMO.PARAMETERS_V;

SELECT
  *
FROM V$IM_SEGMENTS;