CREATE OR REPLACE VIEW CAPSTONE_DEMO.PARAMETER_DURATIONS_V AS SELECT * FROM

(
WITH PARAMETERS_HISTORY_MOD AS

(
SELECT
  NAME,
  VALUE,
  DISPLAY_VALUE,
  SNAPSHOT_TS,
  LAG(VALUE) OVER(PARTITION BY NAME ORDER BY SNAPSHOT_TS) AS PREVIOUS_VALUE,
  LEAD(VALUE) OVER(PARTITION BY NAME ORDER BY SNAPSHOT_TS) AS NEXT_VALUE,
  FIRST_VALUE(SNAPSHOT_TS) OVER(PARTITION BY NAME ORDER BY SNAPSHOT_TS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS FIRST_SNAPSHOT_TS
FROM CAPSTONE_DEMO.PARAMETERS_HISTORY A
)

SELECT
  A.NAME,
  A.VALUE,
  A.DISPLAY_VALUE,
  A.SNAPSHOT_TS AS START_TIME,
  NVL(LEAD(A.SNAPSHOT_TS) OVER(PARTITION BY NAME ORDER BY SNAPSHOT_TS),SYSTIMESTAMP) AS END_TIME
FROM PARAMETERS_HISTORY_MOD A
WHERE VALUE <> NEXT_VALUE
OR VALUE <> PREVIOUS_VALUE
OR PREVIOUS_VALUE IS NULL
ORDER BY
  NAME,
  SNAPSHOT_TS
);


SELECT
  *
FROM CAPSTONE_DEMO.PARAMETER_DURATIONS_V;