CREATE OR REPLACE VIEW CAPSTONE_DEMO.WORKAREA_SIZE_OVER_TIME_V AS

SELECT
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SID,
  A.SQL_ID,
  A.SQL_EXEC_START,
  A.OPERATION_TYPE,
  A.OPERATION_ID,
  A.WORK_AREA_SIZE/POWER(1024,3) AS WORK_AREA_SIZE_GB,
  A.EXPECTED_SIZE/POWER(1024,3) AS EXPECTED_SIZE_GB,
  A.ACTUAL_MEM_USED/POWER(1024,3) AS ACTUAL_MEM_USED_GB,
  A.MAX_MEM_USED/POWER(1024,3) AS MAX_MEM_USED_GB,
  A.NUMBER_PASSES,
  A.TEMPSEG_SIZE/POWER(1024,3) AS TEMPSEG_SIZE_GB
FROM CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY A
WHERE SQL_ID IN (SELECT DISTINCT SQL_ID FROM CAPSTONE_DEMO.SESSION_PROCESS_HISTORY);