CREATE OR REPLACE VIEW CAPSTONE_DEMO.WORK_AREA_SUMMARY_V AS

WITH WORK_AREA_PER_SNAP AS

(
SELECT
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  A.SNAPSHOT_TS,
  SUM(A.WORK_AREA_SIZE/POWER(1024,3)) AS WORK_AREA_SIZE_GB,
  SUM(A.EXPECTED_SIZE/POWER(1024,3)) AS EXPECTED_SIZE_GB,
  SUM(A.ACTUAL_MEM_USED/POWER(1024,3)) AS ACTUAL_MEM_USED_GB,
  SUM(A.MAX_MEM_USED/POWER(1024,3)) AS MAX_MEM_USED_GB,
  SUM(A.TEMPSEG_SIZE/POWER(1024,3)) AS TEMPSEG_SIZE_GB
FROM CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY A
WHERE A.SQL_EXEC_START IS NOT NULL
GROUP BY
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  A.SNAPSHOT_TS
)

SELECT
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  B.DOP,
  B."_PGA_MAX_SIZE",
  B.DB_BIG_TABLE_CACHE_PERCENT,
  B.PARALLEL_DEGREE_POLICY,
  B.DB_CACHE_SIZE,
  B.IM_SIZE,
  MAX(WORK_AREA_SIZE_GB) AS WORK_AREA_SIZE_GB,
  MAX(EXPECTED_SIZE_GB) AS EXPECTED_SIZE_GB,
  MAX(ACTUAL_MEM_USED_GB) AS ACTUAL_MEM_USED_GB,
  MAX(MAX_MEM_USED_GB) AS MAX_MEM_USED_GB,
  NVL(MAX(TEMPSEG_SIZE_GB),0) AS TEMPSEG_SIZE_GB
FROM WORK_AREA_PER_SNAP A
  INNER JOIN CAPSTONE_DEMO.EXPERIMENT_PARAMETERS_V B
    ON A.SQL_EXEC_START = B.SQL_EXEC_START
GROUP BY
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  B.DOP,
  B."_PGA_MAX_SIZE",
  B.DB_BIG_TABLE_CACHE_PERCENT,
  B.PARALLEL_DEGREE_POLICY,
  B.DB_CACHE_SIZE,
  B.IM_SIZE;
  
SELECT
  *
FROM CAPSTONE_DEMO.WORK_AREA_SUMMARY_V;

SELECT
  A.MODULE,
  A.CLIENT_INFO,
  A.SQL_EXEC_START,
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.WORK_AREA_SIZE/POWER(1024,3) AS WORK_AREA_SIZE_GB
FROM CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY A
WHERE SQL_EXEC_START = TO_DATE('12-FEB-2017 14:34:57', 'dd-MON-yyyy hh24:mi:ss');