CREATE OR REPLACE VIEW CAPSTONE_DEMO.WORKAREA_SIZE_OVER_TIME_V AS
/
SELECT
  A.MODULE,
  A.CLIENT_INFO,
  B.DOP,
  B."_PGA_MAX_SIZE",
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  ROUND(CAPSTONE_DEMO.INTERVAL_TO_SEC(A.SNAPSHOT_TS - A.SQL_EXEC_START),0) AS RUN_TIME_SEC,
  A.SQL_ID,
  SUM(A.WORK_AREA_SIZE/POWER(1024,3)) AS WORK_AREA_SIZE_GB,
  SUM(A.EXPECTED_SIZE/POWER(1024,3)) AS EXPECTED_SIZE_GB,
  SUM(A.ACTUAL_MEM_USED/POWER(1024,3)) AS "PGA Used",
  SUM(A.MAX_MEM_USED/POWER(1024,3)) AS MAX_MEM_USED_GB,
  NVL(SUM(A.TEMPSEG_SIZE/POWER(1024,3)),0) AS "Temp Used"
FROM CAPSTONE_DEMO.SQL_WORKAREA_ACTIVE_HISTORY A
  INNER JOIN CAPSTONE_DEMO.DOP_PARAMETERS_V B
    ON A.SQL_EXEC_START = B.SQL_EXEC_START
WHERE A.SQL_EXEC_START IS NOT NULL
GROUP BY
  A.MODULE,
  A.CLIENT_INFO,
  B.DOP,
  B."_PGA_MAX_SIZE",
  A.SNAPSHOT_ID,
  A.SNAPSHOT_TS,
  A.SQL_EXEC_START,
  A.SQL_ID
ORDER BY
  A.SNAPSHOT_TS;

SELECT
  *
FROM CAPSTONE_DEMO.WORKAREA_SIZE_OVER_TIME_V;

