--ALTER SESSION SET WORKAREA_SIZE_POLICY = MANUAL;
--ALTER SESSION SET SORT_AREA_SIZE = 2147483647;
--ALTER SESSION SET HASH_AREA_SIZE = 2147483647;

BEGIN

DBMS_APPLICATION_INFO.SET_MODULE
(
  MODULE_NAME => 'EXPERIMENT_1',
  ACTION_NAME => 'RESOURCE_MONITORING'
);

END;

SELECT /*+ PARALLEL(16) */
  * 
FROM CAPSTONE_DEMO.SINGLE_TABLE_ANALYTICS_V1;

SELECT /*+ PARALLEL(16) */
  * 
FROM CAPSTONE_DEMO.PARENT_CHILD_ANALYTICS_V1;

SELECT /*+ PARALLEL(16) */
  * 
FROM CAPSTONE_DEMO.LEAD_LAG_V1;

SELECT /*+ PARALLEL(16) */
  *
FROM CAPSTONE_DEMO.FILTER_PARENT_CHILD_JOIN_V1;

BEGIN

DBMS_APPLICATION_INFO.SET_MODULE
(
  MODULE_NAME => 'EXPERIMENT_1',
  ACTION_NAME => 'RESOURCE_MONITORING'
);

END;
