SELECT
  'SNAPSHOT_TS TIMESTAMP,' AS COLUMN_PROPERTIES,
  'SYSTIMESTAMP AS SNAPSHOT_TS,' AS COLUMN_SELECT_LIST,
  -1 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  'SNAPSHOT_ID NUMBER,' AS COLUMN_PROPERTIES,
  'NULL AS SNAPSHOT_ID,',
  0 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  CASE
    WHEN DATA_TYPE IN ('LONG','NUMBER', 'CLOB') THEN COLUMN_NAME || ' ' || DATA_TYPE || ','
    WHEN DATA_TYPE IN ('DATE', 'TIMESTAMP') THEN COLUMN_NAME || ' ' || DATA_TYPE || ',' 
    ELSE COLUMN_NAME || ' ' || DATA_TYPE || '(' || DATA_LENGTH || '),' 
  END AS COLUMN_PROPERTIES,
  'A.' || COLUMN_NAME || ',' AS COLUMN_SELECT_LIST,
  COLUMN_ID
FROM ALL_TAB_COLS
WHERE TABLE_NAME = 'V_$IM_USER_SEGMENTS'
AND DATA_TYPE NOT IN ('LONG')
ORDER BY
  COLUMN_ID;
  
WITH COLUMN_LIST AS

(
SELECT
  'SNAPSHOT_TS TIMESTAMP,' AS COLUMN_PROPERTIES,
  'SYSTIMESTAMP AS SNAPSHOT_TS,' AS COLUMN_SELECT_LIST,
  -1 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  'SNAPSHOT_ID NUMBER,' AS COLUMN_PROPERTIES,
  'NULL AS SNAPSHOT_ID,',
  0 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  CASE
    WHEN DATA_TYPE IN ('LONG','NUMBER', 'CLOB') THEN COLUMN_NAME || ' ' || DATA_TYPE || ','
    WHEN DATA_TYPE IN ('DATE', 'TIMESTAMP') THEN COLUMN_NAME || ' ' || DATA_TYPE || ',' 
    ELSE COLUMN_NAME || ' ' || DATA_TYPE || '(' || DATA_LENGTH || '),' 
  END AS COLUMN_PROPERTIES,
  'A.' || COLUMN_NAME || ',' AS COLUMN_SELECT_LIST,
  COLUMN_ID
FROM ALL_TAB_COLS
WHERE TABLE_NAME = :TABLE_NAME
AND DATA_TYPE NOT IN ('LONG')
ORDER BY
  COLUMN_ID
)
  
SELECT 'TRUNCATE TABLE CAPSTONE_DEMO.' || :TABLE_NAME_HIST || ';' AS SQL_TO_GENERATE_SQL FROM DUAL UNION ALL
SELECT 'DROP TABLE CAPSTONE_DEMO.' || :TABLE_NAME_HIST || ';' FROM DUAL UNION ALL
SELECT 'CREATE TABLE CAPSTONE_DEMO.' || :TABLE_NAME_HIST FROM DUAL UNION ALL
SELECT '(' FROM DUAL UNION ALL
SELECT COLUMN_PROPERTIES FROM COLUMN_LIST UNION ALL
SELECT ');' FROM DUAL UNION ALL
SELECT NULL FROM DUAL UNION ALL
SELECT NULL FROM DUAL UNION ALL
SELECT 'INSERT INTO CAPSTONE_DEMO.' || :TABLE_NAME_HIST FROM DUAL UNION ALL
SELECT NULL FROM DUAL UNION ALL
SELECT 'SELECT' FROM DUAL UNION ALL
SELECT COLUMN_SELECT_LIST FROM COLUMN_LIST UNION ALL
SELECT 'FROM ' || :VIEW_NAME || ' A;' FROM DUAL UNION ALL
SELECT NULL FROM DUAL UNION ALL
SELECT 'COMMIT;' FROM DUAL;