SELECT
  *
FROM ALL_TABLES
WHERE TABLE_NAME = 'LEAD_LAG_TEST_V1';

SELECT
  'SNAPSHOT_TS TIMESTAMP,',
  'SYSTIMESTAMP AS SNAPSHOT_TS,',
  -1 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  'SNAPSHOT_ID NUMBER,',
  'NULL AS SNAPSHOT_ID,',
  0 AS COLUMN_ID
FROM DUAL

UNION ALL

SELECT
  CASE
    WHEN DATA_TYPE IN ('LONG','NUMBER') THEN COLUMN_NAME || ' ' || DATA_TYPE || ','
    WHEN DATA_TYPE IN ('DATE', 'TIMESTAMP') THEN COLUMN_NAME || ' ' || DATA_TYPE || ',' 
    ELSE COLUMN_NAME || ' ' || DATA_TYPE || '(' || DATA_LENGTH || '),' 
  END AS COLUMN_PROPERTIES,
  'A.' || COLUMN_NAME || ',' AS COLUMN_SELECT_LIST,
  COLUMN_ID
FROM ALL_TAB_COLS
WHERE TABLE_NAME = 'V_$BT_SCAN_OBJ_TEMPS'
AND DATA_TYPE NOT IN ('LONG')
ORDER BY
  COLUMN_ID;